"use strict";
let x =7;
let y = "dndn";
let z= true;
let s =[];
console.log('The value of my variable x is: ' + x);
console.log('The value of my variable y is: ' + y);
console.log('The value of my variable z is: ' + z);
console.log('The value of my variable s is: ' + s);
console.log(typeof x);console.log("the value of x will be:'number'");
console.log(typeof y);console.log("the value of y will be:'string'");
console.log(typeof z);console.log("the value of z will be:'boolean'");
console.log(typeof s);console.log("the value of s will be:'object'");
if(typeof x===typeof y){console.log('SAME TYPE')}else {console.log('different TYPe')};
if(typeof z===typeof y){console.log('SAME TYPE')}else {console.log('different TYPe')};
if(typeof s===typeof y){console.log('SAME TYPE')}else {console.log('different TYPe')};
if(typeof x===typeof z){console.log('SAME TYPE')}else {console.log('different TYPe')};
if(typeof x===typeof s){console.log('SAME TYPE')}else {console.log('different TYPe')};
if(typeof z===typeof s){console.log('SAME TYPE')}else {console.log('different TYPe')};
